name: Ruby

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and Update
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle update
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GitOAUTHToken }}
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        # repository: # optional, default is 
        # Destination branch to push changes
        # branch: # optional, default is master
        # Determines if force push is used
        # force: # optional
        # Directory to change to before pushing.
        directory: .
